export { default as Title } from './Title';
export { default as Image } from './Image.astro';
export { getFragment as Image_getFragment } from './Image.astro';
export { default as Taxonomies } from './Taxonomies';
export { default as ModificationTime } from './ModificationTime.astro';
export { default as CreationTime } from './CreationTime.astro';
export { getFragment as CreationTime_getFragment } from './CreationTime.astro';
export { getFragment as ModificationTime_getFragment } from './ModificationTime.astro';
export { default as Lead } from './Lead';
