export {default as Title} from './Title';
export {default as Image} from './Image.astro';
export {getFragment as Image_getFragment} from './Image.astro';
export {default as Lead} from './Lead';
export { default as PublicationDate } from './PublicationDate.astro';
export { getFragment as PublicationDate_getFragment } from './PublicationDate.astro';
export { default as ModificationDate } from './ModificationDate.astro';
export { getFragment as ModificationDate_getFragment } from './ModificationDate.astro';
export {default as Authors} from './Authors';
export {default as AuthorsImages} from './AuthorsImages';
export {default as Taxonomies} from './Taxonomies';
