import { APIContext } from "astro";
import { AppContext } from "../types/types";
export declare function UtilsHelper_getCurrentUrl(context: APIContext): string;
export declare function UtilsHelper_convertToInt(input: string | number | undefined): number;
export declare function UtilsHelper_parsePositiveIntFromString(input: string | number | undefined | null): number | undefined;
export declare function UtilsHelper_getValueIfExists(value: any, defaultValue: any): any;
export declare function UtilsHelper_isDevelopmentMode(): boolean;
export declare function UtilsHelper_isMobile(context: any): boolean;
export declare function UtilsHelper_getExtension(src: string): string | null;
export declare function UtilsHelper_asyncSequentialForEach(array: any, callback: any): Promise<void>;
export declare function UtilsHelper_asyncParallelForEach(arr: any, callback: any): Promise<any[]>;
export declare function UtilsHelper_isHomepage(context: any): boolean;
export declare function UtilsHelper_getCurrentPageType(context: any): any;
export declare function UtilsHelper_getCurrentNodeName(context: any): any;
export declare function UtilsHelper_ensureHttps(url: string): string;
export declare function UtilsHelper_getDomain(context: AppContext, alwaysProduction?: boolean): string;
export declare function UtilsHelper_getCurrentUrlWithDomain(context: AppContext, alwaysProduction?: boolean): string;
export declare function UtilsHelper_getCurrentNodeCategoryId(context: AppContext): any;
export declare function UtilsHelper_generateRandomString(length?: number): string;
export declare function UtilsHelper_getQueryParam(param: string, context: AppContext): string | null;
export declare function UtilsHelper_getSearchQueryParamKey(): string;
export declare function UtilsHelper_stripHtmlTags(userInput: string): string;
export declare function UtilsHelper_slugify(slug: string): string;
export declare function UtilsHelper_getErrorMessage(error: unknown): string;
