export let KropkaWebsitesConfig
    = {
    "sections": [],
    "defaultParams": {},
    "paramsDescription": {},
    "modules": {
        "kropka_wdg": {
            "name": "Kropka",
            "description": "",
            "defaultParams": {
                "widgetType": "kropka",
                "mode": "static",
                "target": "",
            },
            "paramsDescription": {
                "widgetType": {
                    "name": "widgetType",
                    "description": "widget type",
                    "type": "textfield",
                    "required": true
                },
                "dv": {
                    "name": "DV",
                    "description": "[Static] - Simply use value in dlApi. [Automatic] - Add pure DV without path (MY_SERVICE_DV) to enable automatic DV path building. DV with '/'  is treated as custom DV (MY_SERVICE_DV/) and path won't be automatically generated by service nodes, but M_ prefix for mobile will be still added.",
                    "type": "textfield",
                    "required": true
                },
                "portalId": {
                    "name": "Portal ID",
                    "description": "",
                    "type": "textfield",
                    "required": true
                },
                "target": {
                    "name": "Target",
                    "description": "[Static] - Simply use value in dlApi with prefix on mobile(M_MY_TARGET). [Automatic] - Leave empty to enable automatic target building. Fill field to override generated value, but M_ prefix for mobile will be still added.",
                    "type": "textfield",
                    "required": false
                },
                "tid": {
                    "name": "Tid",
                    "description": "",
                    "type": "textfield",
                    "required": true
                },
                "mode": {
                    "name": "Mode",
                    "description": "Mode in which the widget will work",
                    "type": "select",
                    "allowBlank": false,
                    "multiSelect": false,
                    "items": ["static", "automatic"]
                },
                "main": {
                    "name": "Main",
                    "description": "[Only in automatic, without custom DV] Used for main page. When empty, automatically will be filled based on language. PL - GLOWNA, other languages - MAIN. Use space as field value to remove this additional string",
                    "type": "textfield",
                    "required": false
                }
            }
        }
    }
}
